min_faves: 150
min_retweet: 10
pages: 30
wait_time: 30
keywords:
  - 'nft'
  - 'crypto'
  - 'bitcoin'
  - 'cryptocurrency'
  - 'aave'
  - 'bnb'
  - 'defi'
  - 'uniswap'
  - 'btc'
  - 'eth'
  - 'ethereum'
  - 'blockchain'
  - 'xrp'
  - 'binance'